-- Traductions fr/de/it des catégories, groupes et sections.
-- Ces colonnes existaient déjà dans la base clonée sans figurer au schéma :
-- IF NOT EXISTS laisse cette base intacte et les crée sur une base neuve.

ALTER TABLE "Group"
  ADD COLUMN IF NOT EXISTS "labelFr" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "labelDe" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "labelIt" TEXT NOT NULL DEFAULT '';

ALTER TABLE "Category"
  ADD COLUMN IF NOT EXISTS "labelFr" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "labelDe" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "labelIt" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "descriptionFr" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "descriptionDe" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "descriptionIt" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "guideIntroFr" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "guideIntroDe" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "guideIntroIt" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "guideClosingFr" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "guideClosingDe" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "guideClosingIt" TEXT NOT NULL DEFAULT '';

ALTER TABLE "GuideSection"
  ADD COLUMN IF NOT EXISTS "headingFr" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "headingDe" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "headingIt" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "bodyFr" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "bodyDe" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "bodyIt" TEXT NOT NULL DEFAULT '';

ALTER TABLE "ProductSection"
  ADD COLUMN IF NOT EXISTS "headingFr" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "headingDe" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "headingIt" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "bodyFr" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "bodyDe" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "bodyIt" TEXT NOT NULL DEFAULT '';
